name: Bug Report
description: Signaler un probleme
labels: ["bug"]
assignees: ["patricklafleur"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      default: 0
      options:
        - Bug
        - Suggestion
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Etapes pour reproduire
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: Appareil
      placeholder: "iPhone 14 Pro"
  - type: input
    id: ios_version
    attributes:
      label: Version iOS
      placeholder: "17.5"
