name: Suggestion
description: Proposer une amelioration
labels: ["enhancement"]
assignees: ["patricklafleur"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Decrivez votre suggestion
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Cas d'utilisation
      description: Dans quel contexte cette fonctionnalite serait utile?
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: Appareil
      placeholder: "iPhone 14 Pro"
  - type: input
    id: ios_version
    attributes:
      label: Version iOS
      placeholder: "17.5"
